# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'demo.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QMainWindow,
    QPlainTextEdit, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(815, 721)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 811, 701))
        self.tabSolo = QWidget()
        self.tabSolo.setObjectName(u"tabSolo")
        self.pushButtonDetectWindow = QPushButton(self.tabSolo)
        self.pushButtonDetectWindow.setObjectName(u"pushButtonDetectWindow")
        self.pushButtonDetectWindow.setGeometry(QRect(650, 80, 131, 24))
        font = QFont()
        font.setFamilies([u"Consolas"])
        font.setPointSize(10)
        self.pushButtonDetectWindow.setFont(font)
        self.label = QLabel(self.tabSolo)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(280, 10, 251, 51))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox = QGroupBox(self.tabSolo)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 120, 781, 71))
        self.pushButtonSelectFolder = QPushButton(self.groupBox)
        self.pushButtonSelectFolder.setObjectName(u"pushButtonSelectFolder")
        self.pushButtonSelectFolder.setGeometry(QRect(660, 30, 101, 24))
        self.pushButtonSelectFolder.setFont(font)
        self.lineEditFolder = QLineEdit(self.groupBox)
        self.lineEditFolder.setObjectName(u"lineEditFolder")
        self.lineEditFolder.setGeometry(QRect(150, 30, 481, 22))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 121, 31))
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setPointSize(12)
        self.label_2.setFont(font2)
        self.groupBox_2 = QGroupBox(self.tabSolo)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 190, 781, 241))
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(440, 30, 71, 31))
        self.label_5.setFont(font2)
        self.listWidgetFiles = QListWidget(self.groupBox_2)
        self.listWidgetFiles.setObjectName(u"listWidgetFiles")
        self.listWidgetFiles.setGeometry(QRect(150, 30, 251, 191))
        self.plainTextInfor = QPlainTextEdit(self.groupBox_2)
        self.plainTextInfor.setObjectName(u"plainTextInfor")
        self.plainTextInfor.setEnabled(False)
        self.plainTextInfor.setGeometry(QRect(530, 30, 231, 191))
        self.plainTextInfor.setReadOnly(True)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 121, 31))
        self.label_3.setFont(font2)
        self.groupBox_4 = QGroupBox(self.tabSolo)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 440, 781, 221))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 121, 31))
        self.label_4.setFont(font2)
        self.groupBox_3 = QGroupBox(self.groupBox_4)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 80, 131, 131))
        self.groupBox_3.setFont(font2)
        self.pushButtonPlay = QPushButton(self.groupBox_3)
        self.pushButtonPlay.setObjectName(u"pushButtonPlay")
        self.pushButtonPlay.setGeometry(QRect(10, 40, 101, 24))
        self.pushButtonPlay.setFont(font)
        self.pushButtonCancel = QPushButton(self.groupBox_3)
        self.pushButtonCancel.setObjectName(u"pushButtonCancel")
        self.pushButtonCancel.setGeometry(QRect(10, 90, 101, 24))
        self.pushButtonCancel.setFont(font)
        self.plainTextEditLogs = QPlainTextEdit(self.groupBox_4)
        self.plainTextEditLogs.setObjectName(u"plainTextEditLogs")
        self.plainTextEditLogs.setGeometry(QRect(150, 20, 611, 191))
        self.tabWidget.addTab(self.tabSolo, "")
        self.tabLan = QWidget()
        self.tabLan.setObjectName(u"tabLan")
        self.label_6 = QLabel(self.tabLan)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(280, 10, 251, 51))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButtonDetectWindow_2 = QPushButton(self.tabLan)
        self.pushButtonDetectWindow_2.setObjectName(u"pushButtonDetectWindow_2")
        self.pushButtonDetectWindow_2.setGeometry(QRect(660, 60, 131, 24))
        self.pushButtonDetectWindow_2.setFont(font)
        self.groupBox_5 = QGroupBox(self.tabLan)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 160, 781, 71))
        self.pushButtonSelectFolder_2 = QPushButton(self.groupBox_5)
        self.pushButtonSelectFolder_2.setObjectName(u"pushButtonSelectFolder_2")
        self.pushButtonSelectFolder_2.setGeometry(QRect(660, 30, 101, 24))
        self.pushButtonSelectFolder_2.setFont(font)
        self.lineEditFolder_2 = QLineEdit(self.groupBox_5)
        self.lineEditFolder_2.setObjectName(u"lineEditFolder_2")
        self.lineEditFolder_2.setGeometry(QRect(150, 30, 481, 22))
        self.label_10 = QLabel(self.groupBox_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 20, 121, 31))
        self.label_10.setFont(font2)
        self.groupBox_6 = QGroupBox(self.tabLan)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 90, 781, 71))
        self.label_7 = QLabel(self.groupBox_6)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 30, 111, 16))
        self.label_7.setFont(font2)
        self.comboBoxRole = QComboBox(self.groupBox_6)
        self.comboBoxRole.setObjectName(u"comboBoxRole")
        self.comboBoxRole.setGeometry(QRect(140, 30, 161, 22))
        self.pushButtonCreateServer = QPushButton(self.groupBox_6)
        self.pushButtonCreateServer.setObjectName(u"pushButtonCreateServer")
        self.pushButtonCreateServer.setGeometry(QRect(640, 30, 131, 24))
        self.pushButtonCreateServer.setFont(font)
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(330, 30, 49, 16))
        self.label_8.setFont(font2)
        self.lineEditIP = QLineEdit(self.groupBox_6)
        self.lineEditIP.setObjectName(u"lineEditIP")
        self.lineEditIP.setGeometry(QRect(390, 30, 241, 22))
        self.pushButtonJoinServer = QPushButton(self.groupBox_6)
        self.pushButtonJoinServer.setObjectName(u"pushButtonJoinServer")
        self.pushButtonJoinServer.setGeometry(QRect(640, 30, 131, 24))
        self.pushButtonJoinServer.setFont(font)
        self.groupBox_7 = QGroupBox(self.tabLan)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 240, 781, 201))
        self.label_11 = QLabel(self.groupBox_7)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(440, 30, 71, 31))
        self.label_11.setFont(font2)
        self.listWidgetFiles_2 = QListWidget(self.groupBox_7)
        self.listWidgetFiles_2.setObjectName(u"listWidgetFiles_2")
        self.listWidgetFiles_2.setGeometry(QRect(150, 30, 251, 161))
        self.plainTextInfor_2 = QPlainTextEdit(self.groupBox_7)
        self.plainTextInfor_2.setObjectName(u"plainTextInfor_2")
        self.plainTextInfor_2.setEnabled(False)
        self.plainTextInfor_2.setGeometry(QRect(530, 30, 231, 161))
        self.plainTextInfor_2.setReadOnly(True)
        self.label_12 = QLabel(self.groupBox_7)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 20, 121, 31))
        self.label_12.setFont(font2)
        self.groupBox_8 = QGroupBox(self.tabLan)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 440, 781, 221))
        self.label_13 = QLabel(self.groupBox_8)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 20, 121, 31))
        self.label_13.setFont(font2)
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(0, 80, 131, 131))
        self.groupBox_9.setFont(font2)
        self.pushButtonPlay_2 = QPushButton(self.groupBox_9)
        self.pushButtonPlay_2.setObjectName(u"pushButtonPlay_2")
        self.pushButtonPlay_2.setGeometry(QRect(10, 40, 101, 24))
        self.pushButtonPlay_2.setFont(font)
        self.pushButtonCancel_2 = QPushButton(self.groupBox_9)
        self.pushButtonCancel_2.setObjectName(u"pushButtonCancel_2")
        self.pushButtonCancel_2.setGeometry(QRect(10, 90, 101, 24))
        self.pushButtonCancel_2.setFont(font)
        self.plainTextEditLogs_2 = QPlainTextEdit(self.groupBox_8)
        self.plainTextEditLogs_2.setObjectName(u"plainTextEditLogs_2")
        self.plainTextEditLogs_2.setGeometry(QRect(150, 20, 611, 191))
        self.tabWidget.addTab(self.tabLan, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"SkyAutoMusic", None))
        self.pushButtonDetectWindow.setText(QCoreApplication.translate("MainWindow", u"Detect Sky Window", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sky Auto Music", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Folder Group", None))
        self.pushButtonSelectFolder.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Select folder", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Files Group", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Infor", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Files", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Action Group", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Logs", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Action", None))
        self.pushButtonPlay.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.pushButtonCancel.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSolo), QCoreApplication.translate("MainWindow", u"Tab Solo", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Sky Auto Music", None))
        self.pushButtonDetectWindow_2.setText(QCoreApplication.translate("MainWindow", u"Detect Sky Window", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Folder Group", None))
        self.pushButtonSelectFolder_2.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Select folder", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Network Action Group", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Select role", None))
        self.pushButtonCreateServer.setText(QCoreApplication.translate("MainWindow", u"Create server", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"IP", None))
        self.pushButtonJoinServer.setText(QCoreApplication.translate("MainWindow", u"Join server", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Files Group", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Infor", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Files", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Action Group", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Logs", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Action", None))
        self.pushButtonPlay_2.setText(QCoreApplication.translate("MainWindow", u"Play", None))
        self.pushButtonCancel_2.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLan), QCoreApplication.translate("MainWindow", u"Tab LAN", None))
    # retranslateUi

